metadata:
  application: showpaas
  version: "7.2.4"
  environment: des
  tenant: global
  domain: swdelivery
  slot: sample
  layer: middleware-redis
  namespace: redis-operator
  platformid: "meccanoarteixo2"
  service: "showpaas"
redis:
  reconciler:
    interval_seconds: 60
  cluster:
    replicas: 1
    namespace: redis-operator
    name: rediscluster-sample
    status: Ready
    health_probe_interval_seconds: 60
    healing_time_seconds: 60
    max_retries: 2
    back_off: 10s
  metrics:
    interval_seconds: 60
    version: 0.10.2.0
    redis_info_keys:
      - keyspace_hits
      - evicted_keys
      - connected_clients
      - total_commands_processed
      - keyspace_misses
      - expired_keys
      - redis_version
      - used_memory_rss
      - maxmemory
      - used_cpu_sys
      - used_cpu_sys_children
      - used_cpu_user
      - used_cpu_user_children
      - total_net_input_bytes
      - total_net_output_bytes
      - aof_base_size
      - aof_current_size
      - mem_aof_buffer

