# SPDX-FileCopyrightText: 2025 INDUSTRIA DE DISEÑO TEXTIL S.A. (INDITEX S.A.)
# SPDX-License-Identifier: Apache-2.0

name: Pull Request Verification
permissions:
  contents: read

on:
  pull_request:
  workflow_dispatch:

jobs:
  repo-linter:
    name: Repo Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: 'Run Repolinter'
        uses: newrelic/repolinter-action@3f4448f855c351e9695b24524a4111c7847b84cb # v1.7.0

  reuse-compliance:
    name: REUSE Compliance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@bb774aa972c2a89ff34781233d275075cbddf542 # v5

  conventional-commits:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: webiny/action-conventional-commits@8bc41ff4e7d423d56fa4905f6ff79209a78776c7 # v1.3.0

  first-contribution:
    name: First Contribution
    runs-on: ubuntu-latest
    steps:
      - uses: plbstl/first-contribution@07f211b42b5db787c5220a4b43f888a904abed34 # v3
        with:
          pr-opened-msg: |
            👋 Thanks for your contribution!

            Before we can review or merge this pull request, we need you to **sign the Contributor License Agreement (CLA)**.

            Please read and sign the CLA at the following link:
            👉 https://github.com/InditexTech/foss/blob/main/CONTRIBUTING.md#prerequisites

            If you have already signed it, feel free to comment here to confirm and we'll verify it.
            If you have any questions, don't hesitate to reach out. Thanks.

            cc: @InditexTech/oso-admins
